// 此档由 scripts/generate-markets.mjs 依 world-countries 自动产生，请勿手动编辑。
// 重新产生：yarn generate:markets

/** [ISO 3166-1 alpha-2, 简体中文名, 英文名]，已依中文名排序。 */
export const RAW_MARKETS: ReadonlyArray<readonly [string, string, string]> = [
  ['AL', '阿尔巴尼亚', 'Albania'],
  ['DZ', '阿尔及利亚', 'Algeria'],
  ['AF', '阿富汗', 'Afghanistan'],
  ['AR', '阿根廷', 'Argentina'],
  ['AE', '阿拉伯联合酋长国', 'United Arab Emirates'],
  ['AW', '阿鲁巴', 'Aruba'],
  ['OM', '阿曼', 'Oman'],
  ['AZ', '阿塞拜疆', 'Azerbaijan'],
  ['EG', '埃及', 'Egypt'],
  ['ET', '埃塞俄比亚', 'Ethiopia'],
  ['IE', '爱尔兰', 'Ireland'],
  ['EE', '爱沙尼亚', 'Estonia'],
  ['AD', '安道尔', 'Andorra'],
  ['AO', '安哥拉', 'Angola'],
  ['AI', '安圭拉', 'Anguilla'],
  ['AG', '安提瓜和巴布达', 'Antigua and Barbuda'],
  ['AT', '奥地利', 'Austria'],
  ['AX', '奥兰群岛', 'Åland Islands'],
  ['AU', '澳大利亚', 'Australia'],
  ['MO', '澳门', 'Macau'],
  ['BB', '巴巴多斯', 'Barbados'],
  ['PG', '巴布亚新几内亚', 'Papua New Guinea'],
  ['BS', '巴哈马', 'Bahamas'],
  ['PK', '巴基斯坦', 'Pakistan'],
  ['PY', '巴拉圭', 'Paraguay'],
  ['PS', '巴勒斯坦', 'Palestine'],
  ['BH', '巴林', 'Bahrain'],
  ['PA', '巴拿马', 'Panama'],
  ['BR', '巴西', 'Brazil'],
  ['BY', '白俄罗斯', 'Belarus'],
  ['BM', '百慕大', 'Bermuda'],
  ['BG', '保加利亚', 'Bulgaria'],
  ['MP', '北马里亚纳群岛', 'Northern Mariana Islands'],
  ['MK', '北马其顿', 'North Macedonia'],
  ['BJ', '贝宁', 'Benin'],
  ['BE', '比利时', 'Belgium'],
  ['IS', '冰岛', 'Iceland'],
  ['PR', '波多黎各', 'Puerto Rico'],
  ['PL', '波兰', 'Poland'],
  ['BA', '波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina'],
  ['BO', '玻利维亚', 'Bolivia'],
  ['BZ', '伯利兹', 'Belize'],
  ['BW', '博茨瓦纳', 'Botswana'],
  ['BT', '不丹', 'Bhutan'],
  ['BF', '布基纳法索', 'Burkina Faso'],
  ['BI', '布隆迪', 'Burundi'],
  ['BV', '布维岛', 'Bouvet Island'],
  ['KP', '朝鲜', 'North Korea'],
  ['GQ', '赤道几内亚', 'Equatorial Guinea'],
  ['DK', '丹麦', 'Denmark'],
  ['DE', '德国', 'Germany'],
  ['TL', '东帝汶', 'Timor-Leste'],
  ['TG', '多哥', 'Togo'],
  ['DO', '多米尼加', 'Dominican Republic'],
  ['DM', '多米尼克', 'Dominica'],
  ['RU', '俄罗斯', 'Russia'],
  ['EC', '厄瓜多尔', 'Ecuador'],
  ['ER', '厄立特里亚', 'Eritrea'],
  ['FR', '法国', 'France'],
  ['TF', '法国南部和南极土地', 'French Southern and Antarctic Lands'],
  ['FO', '法罗群岛', 'Faroe Islands'],
  ['PF', '法属波利尼西亚', 'French Polynesia'],
  ['GF', '法属圭亚那', 'French Guiana'],
  ['VA', '梵蒂冈', 'Vatican City'],
  ['PH', '菲律宾', 'Philippines'],
  ['FJ', '斐济', 'Fiji'],
  ['FI', '芬兰', 'Finland'],
  ['CV', '佛得角', 'Cape Verde'],
  ['FK', '福克兰群岛', 'Falkland Islands'],
  ['GM', '冈比亚', 'Gambia'],
  ['CG', '刚果', 'Republic of the Congo'],
  ['CO', '哥伦比亚', 'Colombia'],
  ['CR', '哥斯达黎加', 'Costa Rica'],
  ['GD', '格林纳达', 'Grenada'],
  ['GL', '格陵兰', 'Greenland'],
  ['GE', '格鲁吉亚', 'Georgia'],
  ['GG', '根西岛', 'Guernsey'],
  ['CU', '古巴', 'Cuba'],
  ['GP', '瓜德罗普岛', 'Guadeloupe'],
  ['GU', '关岛', 'Guam'],
  ['GY', '圭亚那', 'Guyana'],
  ['KZ', '哈萨克斯坦', 'Kazakhstan'],
  ['HT', '海地', 'Haiti'],
  ['KR', '韩国', 'South Korea'],
  ['NL', '荷兰', 'Netherlands'],
  ['BQ', '荷兰加勒比区', 'Caribbean Netherlands'],
  ['HM', '赫德岛和麦当劳群岛', 'Heard Island and McDonald Islands'],
  ['ME', '黑山', 'Montenegro'],
  ['HN', '洪都拉斯', 'Honduras'],
  ['KI', '基里巴斯', 'Kiribati'],
  ['DJ', '吉布提', 'Djibouti'],
  ['KG', '吉尔吉斯斯坦', 'Kyrgyzstan'],
  ['GN', '几内亚', 'Guinea'],
  ['GW', '几内亚比绍', 'Guinea-Bissau'],
  ['CA', '加拿大', 'Canada'],
  ['GH', '加纳', 'Ghana'],
  ['GA', '加蓬', 'Gabon'],
  ['KH', '柬埔寨', 'Cambodia'],
  ['CZ', '捷克', 'Czechia'],
  ['ZW', '津巴布韦', 'Zimbabwe'],
  ['CM', '喀麦隆', 'Cameroon'],
  ['QA', '卡塔尔', 'Qatar'],
  ['KY', '开曼群岛', 'Cayman Islands'],
  ['CC', '科科斯', 'Cocos (Keeling) Islands'],
  ['KM', '科摩罗', 'Comoros'],
  ['CI', '科特迪瓦', 'Ivory Coast'],
  ['KW', '科威特', 'Kuwait'],
  ['HR', '克罗地亚', 'Croatia'],
  ['KE', '肯尼亚', 'Kenya'],
  ['CK', '库克群岛', 'Cook Islands'],
  ['CW', '库拉索', 'Curaçao'],
  ['LV', '拉脱维亚', 'Latvia'],
  ['LS', '莱索托', 'Lesotho'],
  ['LA', '老挝', 'Laos'],
  ['LB', '黎巴嫩', 'Lebanon'],
  ['LT', '立陶宛', 'Lithuania'],
  ['LR', '利比里亚', 'Liberia'],
  ['LY', '利比亚', 'Libya'],
  ['LI', '列支敦士登', 'Liechtenstein'],
  ['RE', '留尼旺岛', 'Réunion'],
  ['LU', '卢森堡', 'Luxembourg'],
  ['RW', '卢旺达', 'Rwanda'],
  ['RO', '罗马尼亚', 'Romania'],
  ['MG', '马达加斯加', 'Madagascar'],
  ['IM', '马恩岛', 'Isle of Man'],
  ['MV', '马尔代夫', 'Maldives'],
  ['MT', '马耳他', 'Malta'],
  ['MW', '马拉维', 'Malawi'],
  ['MY', '马来西亚', 'Malaysia'],
  ['ML', '马里', 'Mali'],
  ['MH', '马绍尔群岛', 'Marshall Islands'],
  ['MQ', '马提尼克', 'Martinique'],
  ['YT', '马约特', 'Mayotte'],
  ['MU', '毛里求斯', 'Mauritius'],
  ['MR', '毛里塔尼亚', 'Mauritania'],
  ['US', '美国', 'United States'],
  ['UM', '美国本土外小岛屿', 'United States Minor Outlying Islands'],
  ['AS', '美属萨摩亚', 'American Samoa'],
  ['VI', '美属维尔京群岛', 'United States Virgin Islands'],
  ['MN', '蒙古', 'Mongolia'],
  ['MS', '蒙特塞拉特', 'Montserrat'],
  ['BD', '孟加拉国', 'Bangladesh'],
  ['PE', '秘鲁', 'Peru'],
  ['FM', '密克罗尼西亚', 'Micronesia'],
  ['MM', '缅甸', 'Myanmar'],
  ['CD', '民主刚果', 'DR Congo'],
  ['MD', '摩尔多瓦', 'Moldova'],
  ['MA', '摩洛哥', 'Morocco'],
  ['MC', '摩纳哥', 'Monaco'],
  ['MZ', '莫桑比克', 'Mozambique'],
  ['MX', '墨西哥', 'Mexico'],
  ['NA', '纳米比亚', 'Namibia'],
  ['ZA', '南非', 'South Africa'],
  ['AQ', '南极洲', 'Antarctica'],
  ['GS', '南乔治亚', 'South Georgia'],
  ['SS', '南苏丹', 'South Sudan'],
  ['NR', '瑙鲁', 'Nauru'],
  ['NI', '尼加拉瓜', 'Nicaragua'],
  ['NP', '尼泊尔', 'Nepal'],
  ['NE', '尼日尔', 'Niger'],
  ['NG', '尼日利亚', 'Nigeria'],
  ['NU', '纽埃', 'Niue'],
  ['NO', '挪威', 'Norway'],
  ['NF', '诺福克岛', 'Norfolk Island'],
  ['PW', '帕劳', 'Palau'],
  ['PN', '皮特凯恩群岛', 'Pitcairn Islands'],
  ['PT', '葡萄牙', 'Portugal'],
  ['JP', '日本', 'Japan'],
  ['SE', '瑞典', 'Sweden'],
  ['CH', '瑞士', 'Switzerland'],
  ['SV', '萨尔瓦多', 'El Salvador'],
  ['WS', '萨摩亚', 'Samoa'],
  ['RS', '塞尔维亚', 'Serbia'],
  ['SL', '塞拉利昂', 'Sierra Leone'],
  ['SN', '塞内加尔', 'Senegal'],
  ['CY', '塞浦路斯', 'Cyprus'],
  ['SC', '塞舌尔', 'Seychelles'],
  ['SA', '沙特阿拉伯', 'Saudi Arabia'],
  ['BL', '圣巴泰勒米', 'Saint Barthélemy'],
  ['CX', '圣诞岛', 'Christmas Island'],
  ['ST', '圣多美和普林西比', 'São Tomé and Príncipe'],
  ['SH', '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 'Saint Helena, Ascension and Tristan da Cunha'],
  ['KN', '圣基茨和尼维斯', 'Saint Kitts and Nevis'],
  ['LC', '圣卢西亚', 'Saint Lucia'],
  ['MF', '圣马丁', 'Saint Martin'],
  ['SX', '圣马丁岛', 'Sint Maarten'],
  ['SM', '圣马力诺', 'San Marino'],
  ['PM', '圣皮埃尔和密克隆', 'Saint Pierre and Miquelon'],
  ['VC', '圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines'],
  ['LK', '斯里兰卡', 'Sri Lanka'],
  ['SK', '斯洛伐克', 'Slovakia'],
  ['SI', '斯洛文尼亚', 'Slovenia'],
  ['SJ', '斯瓦尔巴特', 'Svalbard and Jan Mayen'],
  ['SZ', '斯威士兰', 'Eswatini'],
  ['SD', '苏丹', 'Sudan'],
  ['SR', '苏里南', 'Suriname'],
  ['SB', '所罗门群岛', 'Solomon Islands'],
  ['SO', '索马里', 'Somalia'],
  ['TJ', '塔吉克斯坦', 'Tajikistan'],
  ['TW', '台湾', 'Taiwan'],
  ['TH', '泰国', 'Thailand'],
  ['TZ', '坦桑尼亚', 'Tanzania'],
  ['TO', '汤加', 'Tonga'],
  ['TC', '特克斯和凯科斯群岛', 'Turks and Caicos Islands'],
  ['TT', '特立尼达和多巴哥', 'Trinidad and Tobago'],
  ['TN', '突尼斯', 'Tunisia'],
  ['TV', '图瓦卢', 'Tuvalu'],
  ['TR', '土耳其', 'Türkiye'],
  ['TM', '土库曼斯坦', 'Turkmenistan'],
  ['TK', '托克劳', 'Tokelau'],
  ['WF', '瓦利斯和富图纳群岛', 'Wallis and Futuna'],
  ['VU', '瓦努阿图', 'Vanuatu'],
  ['GT', '危地马拉', 'Guatemala'],
  ['VE', '委内瑞拉', 'Venezuela'],
  ['BN', '文莱', 'Brunei'],
  ['UG', '乌干达', 'Uganda'],
  ['UA', '乌克兰', 'Ukraine'],
  ['UY', '乌拉圭', 'Uruguay'],
  ['UZ', '乌兹别克斯坦', 'Uzbekistan'],
  ['ES', '西班牙', 'Spain'],
  ['EH', '西撒哈拉', 'Western Sahara'],
  ['GR', '希腊', 'Greece'],
  ['HK', '香港', 'Hong Kong'],
  ['SG', '新加坡', 'Singapore'],
  ['NC', '新喀里多尼亚', 'New Caledonia'],
  ['NZ', '新西兰', 'New Zealand'],
  ['HU', '匈牙利', 'Hungary'],
  ['SY', '叙利亚', 'Syria'],
  ['JM', '牙买加', 'Jamaica'],
  ['AM', '亚美尼亚', 'Armenia'],
  ['YE', '也门', 'Yemen'],
  ['IQ', '伊拉克', 'Iraq'],
  ['IR', '伊朗', 'Iran'],
  ['IL', '以色列', 'Israel'],
  ['IT', '意大利', 'Italy'],
  ['IN', '印度', 'India'],
  ['ID', '印度尼西亚', 'Indonesia'],
  ['GB', '英国', 'United Kingdom'],
  ['VG', '英属维尔京群岛', 'British Virgin Islands'],
  ['IO', '英属印度洋领地', 'British Indian Ocean Territory'],
  ['JO', '约旦', 'Jordan'],
  ['VN', '越南', 'Vietnam'],
  ['ZM', '赞比亚', 'Zambia'],
  ['JE', '泽西岛', 'Jersey'],
  ['TD', '乍得', 'Chad'],
  ['GI', '直布罗陀', 'Gibraltar'],
  ['CL', '智利', 'Chile'],
  ['CF', '中非共和国', 'Central African Republic'],
  ['CN', '中国', 'China'],
]
